#
# Copyright 2018 Stratum Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: 2.1
var_1: &bazel_cache_key bazel-cache-{{ checksum "Dockerfile.build" }}-{{ checksum "WORKSPACE" }}-{{ checksum "bazel/deps.bzl" }}
var_2: &bazel_cache_path ~/.cache/bazel

orbs:
  stratum_bazel_orb:
    jobs:
      build:
        parameters:
          path:
            description: bazel path to build
            type: string
            default: //...:all
        docker:
          - image: stratumproject/build:latest
        steps:
          - checkout
          - restore_cache:
              key: *bazel_cache_key
          - run: bazel build -j 1 <<parameters.path>>
          - save_cache:
              key: *bazel_cache_key
              paths:
                - *bazel_cache_path
      test:
        parameters:
          path:
            description: bazel path to test
            type: string
            default: //...:all
        docker:
          - image: stratumproject/build:latest
        steps:
          - checkout
          - restore_cache:
              key: *bazel_cache_key
          - run: bazel test -j 1 <<parameters.path>>
          - save_cache:
              key: *bazel_cache_key
              paths:
                - *bazel_cache_path

workflows:
  version: 2.1
  library:
    jobs:
      - stratum_bazel_orb/build:
          path: //stratum/lib:all
  binary:
    jobs:
      - stratum_bazel_orb/build:
          name: stratum_dummy
          path: //stratum/hal/bin/dummy:all
  test:
    jobs:
      - stratum_bazel_orb/test:
          path: //stratum/lib:all    
